services:

  open-gateway:
    image: registry.makan-system.ir/open-gateway:latest
    container_name: open-gateway

    environment:
      ASPNETCORE_URLS: "http://+:8080"
      ASPNETCORE_ENVIRONMENT: "Development"
    ports:
      - "8004:8080"
    networks:
      - vms-network

networks:
  vms-network:
    driver: bridge
