services:

  open-gateway:
    container_name: open-gateway

    build:
      context: ./Open-Gateway
      dockerfile: Dockerfile

    environment:
      ASPNETCORE_URLS: "http://+:8080"
      ASPNETCORE_ENVIRONMENT: "Development"

    ports:
      - "8004:8080"